spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth2
    username: root
    password: 55555
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml


#jwt 配置
#eg: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ5eS1yb2xlcyI6W3siYXV0aG9yaXR5Ijoic2hvd01lbWJlciJ9LHsiYXV0aG9yaXR5IjoiYWRkTWVtYmVyIn0seyJhdXRob3JpdHkiOiJ1cGRhdGVNZW1iZXIifV0sInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MjE2NTMzOTEsImV4cCI6MTYyMTY1Mzk5NX0.91rhOGR9F3OEPOYZvZWD4LdwgLxTYchENaliMwc9Vkw
jwt:
  tokenHeader: token #JWT存储的请求头
  # jwt 密匙
  secret: yy-secret
  # 超时时间 1 小时 60*60
  expirition: 3600
  role:
    claims: yy-roles
  tokenHead: Bearer  #JWT负载中拿到开头